version: 2.1

# Copyright @carlaalexander.ca
# "Borrowed" from: https://carlalexander.ca/continuous-deployment-wordpress-directory-circleci/
#
# Updated by @eighty20results to match needs for Eight/20 Results plugin development & testing

references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
                 /tmp/wordpress
  WP_HOST: &WP_HOST
             e20r-single-use-trial.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
                        e20r-single-use-trial
  WP_ORG_USERNAME: &WP_ORG_USERNAME
                     eighty20results
  WP_DEPENDENCY_LIST: &WP_DEPENDENCY_LIST
            paid-memberships-pro pmpro-payfast

  DB_HOST: &DB_HOST
            wordpress
  DB_USER: &DB_USER
            wordpress
  DB_PASS: &DB_PASS
            wordpress
  DB_NAME: &DB_NAME
             wordpress
  DEV_COMPOSER: &DEV_COMPOSER
                  composer.json
  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7-apache-browsers
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_DEPENDENCY_LIST: *WP_DEPENDENCY_LIST
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
    working_directory: ~/e20r-single-use-trial

  workspace_root: &workspace_root
                    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_inc: &copy_inc
    run:
      name: Copy inc directory
      command: if [[ -d /tmp/inc ]]; then cp -R /tmp/inc .; fi

  install_subversion: &install_subversion
    run:
      name: Install subversion
      command: sudo -E apt-get install subversion -y

  # Installs composer dependencies
  #
  dependency_install: &dependency_install
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_inc
      - run:
          name: Install the PHPUnit package for this version of PHP
          command: |
            if [[ -f composer.lock ]]; then
              echo "Remove the composer.lock file"
              rm -f composer.lock
            fi
            echo "Select phpunit for PHP ${PHP_VERSION}"
            # Install the specified version of PHPUnit depending on the PHP version:
            case "${PHP_VERSION}" in
              7.[3-4].*|nightly)
                # Use composer to install a compatible version of phpunit
                inc/bin/composer global require "phpunit/phpunit=^9.0"
                ;;
              7.2.*)
                echo "Using PHPUnit 6.0 for PHP ${PHP_VERSION}"
                inc/bin/composer global require "phpunit/phpunit<=6.0.*"
                ;;
              5.6.*|7.[0-1].*)
                echo "Using PHPUnit 5.7 for PHP ${PHP_VERSION}"
                inc/bin/composer global require "phpunit/phpunit<=5.7.*"
                ;;
              *)
                echo "No PHPUnit version handling for PHP version ${PHP_VERSION}"
                exit 1
                ;;
            esac


  # Default configuration for all Acceptance testing jobs
  #
  acceptance_job: &acceptance_job
    <<: *container_config
    docker:
      - image: circleci/php:7-apache-browsers
      - image: circleci/mariadb:10.4-focal
    steps:
      - checkout
      - run:
          name: Add WordPress host to hosts file
          command: echo "127.0.0.1 ${WP_HOST}" | sudo -E tee -a /etc/hosts
      - *attach_workspace
      - *copy_inc
#      - *dependency_install
      - run:
          name: Figure out the distro/version
          command: sudo -E cat /etc/*-release
#      - run:
#          name: Install MariaDB client
#          command: sudo -E apt install mariadb-client-10.1
      - run:
          name: Install MariaDB (MySQL) PHP extension
          command: |
            sudo -E docker-php-ext-install pdo_mysql
            sudo -E docker-php-ext-enable pdo_mysql
      - run:
          name: Setup WordPress
          command: .circleci/setup-$WP_TYPE.sh
      - run:
          name: Start PHP server
          command: sudo -E php -S $WP_HOST:80 -t $WP_CORE_DIR
          background: True
      - run:
          name: Run CodeCeption Acceptance tests
          # TODO: Transition to codeception test execution for WordPress
          command: inc/bin/codecept --format progress --tags=$WP_TYPE
      - store_test_results:
          path: test-results

  # Default configuration for all phpunit testing jobs
  #
  phpunit_job: &phpunit_job
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_inc
#      - *dependency_install
      - run:
          name: Run PHP unit tests
          command: inc/bin/phpunit --bootstrap tests/bootstrap.php --configuration phpunit.xml tests/unittests/test_*.php
      - store_test_results:
          path: test-results

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install WordPress
          command: bash .circleci/install-wp.sh
      - persist_to_workspace:
          root: .
          paths:
            - inc
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress

  code_quality:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_inc
#      - *dependency_install
      - run:
          name: Run code quality tests
          command: inc/bin/grumphp run --testsuite=code_quality

  test_php74:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.4

  test_php73:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.3

  acceptance_singlesite:
    <<: *acceptance_job
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_DEPENDENCY_LIST: *WP_DEPENDENCY_LIST
      - WP_TYPE: singlesite

  acceptance_multisite:
    <<: *acceptance_job
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_DEPENDENCY_LIST: *WP_DEPENDENCY_LIST
      - WP_TYPE: multisite

#  deploy_assets:
#    <<: *container_config
#    steps:
#      - checkout
#      - *attach_workspace
#      # - *install_subversion
#      - run:
#          name: Deploy assets to WordPress plugin directory
#          command: .circleci/deploy-assets.sh
#
  release_plugin:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Create new release for GitHub
          # TODO: Create script to generate a release tag for the repository
          command: .circleci/release-plugin.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
#      - deploy_assets:
#          filters:
#            branches:
#              only:
#                - master
#                - release-*
      - code_quality:
          requires:
            - build
      - test_php74:
          requires:
            - code_quality
      - test_php73:
          requires:
            - code_quality
      - acceptance_singlesite:
          filters:
            branches:
              only:
                - master
                - release-*
          requires:
            - test_php74
            - test_php73
#      - acceptance_multisite:
#          filters:
#            branches:
#              only:
#                - master
#                - release-*
#          requires:
#            - test_php74
#            - test_php73
      - release_plugin:
          filters:
            branches:
              only:
                - release-*
          requires:
            - acceptance_singlesite
#            - acceptance_multisite
